version: "3.8"

services: 
  lb:
    image: learndocker-lb:latest
    build:
      context: ./load-balancer
    depends_on: 
      - webapp
    ports:
      - 80:80
    environment: 
      - PROXY_UPSTREAM

  pg:
    image: postgres:12.3-alpine
    environment: 
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pg-data:/var/lib/postgresql/data

  webapp:
    image: jfahrer/demo_web_app:wait_for_pg
    depends_on: 
      - pg
    # ports:
    #   - 9292:9292
    environment: 
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
  

  # alpine:
  #   image: alpine:latest
  #   stdin_open: true
  #   tty: true
  #   command: sh

volumes: 
  pg-data:
